version: '3.7'

services:
  web:
    image: node:12-alpine
    volumes:
      - p11k:/p11k:delegated
    working_dir: /p11k/src/services/web
    depends_on:
      - graphql
    environment:
      NEXT_TELEMETRY_DISABLED: 'true'
      NODE_ENV: development
    ports:
      - 3000:3000
    command: yarn next -p 3000

volumes:
  p11k:
    driver: local
    driver_opts:
      type: none
      device: ${ROOT_DIR}
      o: bind
