version: '3.7'

services:
  postgres:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: accounts
      MONGO_INITDB_ROOT_PASSWORD: developer_password
      MONGO_INITDB_ROOT_USERNAME: developer
    ports:
      - 27017:27017
