version: '3.7'

services:
  graphql:
    image: node:12-alpine
    volumes:
      - p11k:/p11k:cached
    working_dir: /p11k/src/services/graphql
    depends_on:
      - account
    environment:
      NODE_ENV: development
      PORT: '4000'
    ports:
      - 4000:4000
    command: yarn nodemon

volumes:
  p11k:
    driver: local
    driver_opts:
      type: none
      device: ${ROOT_DIR}
      o: bind
