version: '3.7'

services:
  graphql:
    image: node:12-alpine
    volumes:
      - p11k:/p11k:cached
    working_dir: /p11k/src/services/graphql
    depends_on:
      - account
    env_file: ../.env
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    environment:
      PORT: ${PORT:-4000}
    command: yarn nodemon

volumes:
  p11k:
    driver: local
    driver_opts:
      type: none
      device: ${ROOT_DIR}
      o: bind
