version: '3.7'

services:
  account:
    image: node:12-alpine
    volumes:
      - p11k:/p11k:cached
    working_dir: /p11k/src/services/account
    depends_on:
      - mongo
    env_file: ../.env
    ports:
      - ${PORT:-4001}:${PORT:-4001}
    environment:
      PORT: ${PORT:-4001}
    command: yarn nodemon

  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: accounts
      MONGO_INITDB_ROOT_PASSWORD: developer_password
      MONGO_INITDB_ROOT_USERNAME: developer
    ports:
      - 27017:27017
    logging:
      driver: none

volumes:
  p11k:
    driver: local
    driver_opts:
      type: none
      device: /Users/fredrik/Documents/repositories/private/p11k
      o: bind
