version: '3.7'

services:
  graphql:
    image: node:12-alpine
    restart: always
    volumes:
      - p11k:/p11k:cached
    working_dir: /p11k/packages/private/graphql
    depends_on:
      - account
    env_file: ${GRAPHQL_DIR}/.env
    environment:
      ACCOUNT_URL: http://account:5000
      PORT: 4000
    ports:
      - 4000:4000
    command: yarn nodemon

volumes:
  p11k:
    driver: local
    driver_opts:
      type: none
      device: ${ROOT_DIR}
      o: bind
