version: '3.7'

services:
  web:
    image: node:12-alpine
    volumes:
      - p11k:/p11k:cached
    working_dir: /p11k/packages/private/web
    depends_on:
      - graphql
    env_file: ${WEB_DIR}/.env
    environment:
      GRAPHQL_URL: 'http://host.docker.internal:4000/graphql'
      PORT: 3000
    ports:
      - 3000:3000
    command: yarn nodemon

volumes:
  p11k:
    driver: local
    driver_opts:
      type: none
      device: ${ROOT_DIR}
      o: bind
