version: '3.7'

services:
  web:
    image: node:12-alpine
    volumes:
      - p11k:/p11k:cached
    working_dir: /p11k/src/services/web
    depends_on:
      - graphql
    env_file: .env
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    command: yarn next -p ${PORT:-3000}

volumes:
  p11k:
    driver: local
    driver_opts:
      type: none
      device: $PWD/../../../
      o: bind
